
# Pair Programming NumPy IV

## Lección 4 - NumPy IV: Conjuntos, distribuciones aleatorias
### Judith Mellidez y Sonia Ruiz

Manos a la obra con la última lección de NumPy. En este caso pondremos en práctica 
como generar arrays que sigan ciertas distribuciones, así como las operaciones de 
teoría de conjuntos básicas.

In [54]:
#Importamos la libreria Numpy y la libreria random (para generar numeros pseudoaleatorios para distintas distribuciones)
import numpy as np
import random

1. ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [55]:
np.random.seed(1)
array1=np.random.sample((3,5))
array1

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01],
       [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01,
        5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02]])

In [56]:
np.random.seed(1)
array2=np.random.sample((3,5))
array2

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01],
       [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01,
        5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02]])

2. Cread los siguientes arrays:
- Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.


In [57]:
#Utilizamos el metodo "np.random.uniform()" para generar muestras aleatroias de distribucion uniforme, con valores tipo float.
array3=np.random.uniform(0,10, size=(2,3,5))
array3

array([[[6.7046751 , 4.17304802, 5.58689828, 1.40386939, 1.98101489],
        [8.00744569, 9.68261576, 3.13424178, 6.92322616, 8.76389152],
        [8.94606664, 0.85044211, 0.39054783, 1.6983042 , 8.78142503]],

       [[0.98346834, 4.21107625, 9.5788953 , 5.33165285, 6.91877114],
        [3.15515631, 6.86500928, 8.34625672, 0.18288277, 7.50144315],
        [9.88861089, 7.48165654, 2.80443992, 7.89279328, 1.03226007]]])

In [58]:
#Quitamos los decimales a los elementos del array
array3=np.round(array3,decimals=0)
array3

array([[[ 7.,  4.,  6.,  1.,  2.],
        [ 8., 10.,  3.,  7.,  9.],
        [ 9.,  1.,  0.,  2.,  9.]],

       [[ 1.,  4., 10.,  5.,  7.],
        [ 3.,  7.,  8.,  0.,  8.],
        [10.,  7.,  3.,  8.,  1.]]])

In [59]:
#Utilizamos el metodo el "np.unique()" para extraer los valores unicos y ordenados de nuestro array. 
array3_unique=np.unique(array3)
array3_unique

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

- Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [60]:
#Generamos un array con elementos con distribucion binomial, el numero de pruebas es igual a 10 (n= numero de ensayos/pruebas)
#  y la probabilidad es 0.3 (p=probabilidad de exitos, es decir, de obtener n).
array4=np.random.binomial(10,0.3, size=(2,3,5))
array4

array([[[3, 5, 2, 2, 1],
        [0, 4, 2, 2, 3],
        [1, 3, 1, 3, 4]],

       [[1, 3, 4, 3, 1],
        [3, 4, 3, 5, 3],
        [5, 1, 1, 4, 3]]])

In [61]:
#Utilizamos el metodo el "np.unique()" para extraer los valores unicos y ordenados de nuestro array.
array4_unique=np.unique(array4)
array4_unique

array([0, 1, 2, 3, 4, 5])

3. En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

- Elementos comunes entre los dos arrays

  
    


In [62]:
#Nos muestra los elementos ordenados que se encuentran en ambos arrays.
comunes_1=np.intersect1d(array3_unique,array4_unique)
comunes_1

array([0., 1., 2., 3., 4., 5.])

- Unión de los dos arrays

In [63]:
#Obtenemos un array ordenado con los elementos comunes a ambos arrays.
union_1=np.union1d(array3_unique,array4_unique)
union_1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

  - ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

In [64]:
#Obenemos un array ordenado con los valores unicos que estan en el array3_unique pero no en el array4_unique.
diferentes_1=np.setdiff1d(array3_unique, array4_unique)
diferentes_1


array([ 6.,  7.,  8.,  9., 10.])

4. Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, 
con los siguientes nombres array1 y array2.

In [65]:
#Creamos un array bidimensional con el metodo random.randint, donde coge numeros aleatorios, tipo integer, dentro
#  del rango que le especifiquemos.
array_1=np.random.randint(1,100,80)
array_1

array([ 8, 46, 69, 58, 83, 97, 14, 11, 24, 82,  8, 25, 75, 93, 21, 33, 13,
       66, 95, 61, 25, 83, 98,  3, 93, 99, 11, 55, 97, 83, 87, 71, 67, 72,
       49, 55, 16,  6, 18, 43, 21, 49, 23, 14, 98, 54, 85, 11, 97, 56, 62,
       57, 90, 22, 97, 84, 26, 15, 14, 85, 44,  7, 78, 57, 60, 16, 25, 10,
       67, 72, 54, 70, 37, 22, 41, 78, 92, 50, 48, 78])

In [66]:
array_2=np.random.randint(1,100,80)
array_2

array([41, 79, 46, 88, 17, 29, 46, 68, 67, 79, 47,  1, 30, 64, 76, 36, 54,
       94, 34,  3, 85, 84, 49, 55, 33, 29, 56, 83, 32, 29, 95, 75,  9, 33,
        9, 85, 78, 51, 80, 42, 65, 84, 25, 21, 45, 16, 31, 92, 15, 20, 27,
       87,  8, 54, 48, 61, 35, 33, 20, 68, 25, 84, 95, 39, 48,  6, 80, 64,
       88, 33, 43, 75, 67, 89, 99, 31, 18, 69, 65, 61])

- Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array_1 y array_2.

In [67]:
array_1=np.unique(array_1)
array_1

array([ 3,  6,  7,  8, 10, 11, 13, 14, 15, 16, 18, 21, 22, 23, 24, 25, 26,
       33, 37, 41, 43, 44, 46, 48, 49, 50, 54, 55, 56, 57, 58, 60, 61, 62,
       66, 67, 69, 70, 71, 72, 75, 78, 82, 83, 84, 85, 87, 90, 92, 93, 95,
       97, 98, 99])

In [68]:
array_2=np.unique(array_2)
array_2

array([ 1,  3,  6,  8,  9, 15, 16, 17, 18, 20, 21, 25, 27, 29, 30, 31, 32,
       33, 34, 35, 36, 39, 41, 42, 43, 45, 46, 47, 48, 49, 51, 54, 55, 56,
       61, 64, 65, 67, 68, 69, 75, 76, 78, 79, 80, 83, 84, 85, 87, 88, 89,
       92, 94, 95, 99])

- Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array_3.

In [69]:
array_3=np.setdiff1d(array_1, array_2)
array_3

array([ 7, 10, 11, 13, 14, 22, 23, 24, 26, 37, 44, 50, 57, 58, 60, 62, 66,
       70, 71, 72, 82, 90, 93, 97, 98])

- Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array_4.

In [70]:
array_4=np.setdiff1d(array_2, array_1)
array_4

array([ 1,  9, 17, 20, 27, 29, 30, 31, 32, 34, 35, 36, 39, 42, 45, 47, 51,
       64, 65, 68, 76, 79, 80, 88, 89, 94])

- Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

In [71]:
array_5=np.intersect1d(array_1,array_2)
array_5

array([ 3,  6,  8, 15, 16, 18, 21, 25, 33, 41, 43, 46, 48, 49, 54, 55, 56,
       61, 67, 69, 75, 78, 83, 84, 85, 87, 92, 95, 99])

- ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [72]:
# Al realizar la suma de la longitud 'len' de los elementos presentes en array_1 (elementos unicos del array1 original) 
# mas el array_4 (presentes en en array_2 pero NO en el array_1) obtenemos la longitud del array original
#  array_1 (longitud del array original 'len'=80 ).
# Al realizar la suma de la longitud 'len' de los elementos presentes en array_2 (elementos unicos del array2 original) 
# mas el array_3 (presentes en en array_1 pero NO en el array_2) obtenemos la longitud del array original
#  array_2 (longitud del array original 'len'=80 ).


a1=len(array_1)
print('La longitud del array_1 es:', a1)

a2=len(array_2)
print(f'La longitud del array_2 es:', a2)

a3=len(array_3)
print(f'La longitud del array_3 es:', a3)

a4=len(array_4)
print(f'La longitud del array_4 es:', a4)

a5=len(array_5)
print(f'La longitud del array_5 es:', a5)

La longitud del array_1 es: 54
La longitud del array_2 es: 55
La longitud del array_3 es: 25
La longitud del array_4 es: 26
La longitud del array_5 es: 29


Happy coding 😀