# Ejercicios Pair Programming - Modulo 2 - Sprint 1 
## Lección 1 - NumPy I: Introducción a NumPy
### Judith Mellidez y Sonia Ruiz

En el ejercicio de hoy vamos a empezar a trabajar con NumPy. El objetivo de estos ejericicios es que creeis una serie de arrays, y hagáis una serie de operaciones matemáticas con ellos.

1.Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.
📌 Nota
El array de 2 dimensiones debe ser de 2 filas y 3 columnas
El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [5]:
#Importamos la libreria numpy
import numpy as np

In [6]:
# Creamos un array unidimensional 
array1=np.random.randint(0,20,(5))
print(array1)

[ 3  6 11 13  4]


In [7]:
# Creamos un array bidimensional 
array2=np.random.rand(2,3)
print(array2)

[[0.95651452 0.1367402  0.98800117]
 [0.81457687 0.00921118 0.40956377]]


In [8]:
# Creamos un array multidimensional 
array3=np.random.rand(2,3,5)
print(array3)

[[[0.1410468  0.95019386 0.54113352 0.0053564  0.18059409]
  [0.87020178 0.48001633 0.36717463 0.22932352 0.01852361]
  [0.73326857 0.9606754  0.7004347  0.51885076 0.78091004]]

 [[0.66254267 0.15375457 0.83123788 0.90914176 0.71142385]
  [0.64061168 0.66418215 0.88003233 0.60433378 0.93606976]
  [0.37428451 0.49452781 0.32513758 0.81241592 0.80016041]]]


2.Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [9]:
#Creamos una funcion para comprobar las propiedades de un array.
def propiedades_array(array):
    lista_array=[]
    shape=array.shape
    print('Su forma es', shape)
    size=array.size
    print('Su tamaño es', size)
    dimension=array.ndim
    print('Sus dimensiones son', dimension)
    tipo=array.dtype
    print('El tipo de dato almacenado es', tipo)
    return

In [10]:
print(propiedades_array(array1))
print('---------')
print(propiedades_array(array2))
print('---------')
print(propiedades_array(array3))

Su forma es (5,)
Su tamaño es 5
Sus dimensiones son 1
El tipo de dato almacenado es int64
None
---------
Su forma es (2, 3)
Su tamaño es 6
Sus dimensiones son 2
El tipo de dato almacenado es float64
None
---------
Su forma es (2, 3, 5)
Su tamaño es 30
Sus dimensiones son 3
El tipo de dato almacenado es float64
None


3.Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [21]:
#Con la matriz identidad creamos un array con valores 1 en la diagonal y los demas valores son 0.
array4=np.identity(3)
print(array4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4.Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [22]:
#Creamos un array de 3 dimensiones donde todos sus valores son 1.
array5=np.ones_like(array3)
print(array5)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


5.Es el momento de hacer algunas operaciones entre arrays.
- ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

In [23]:
print(array2)

[[0.65063124 0.25435173 0.27773023]
 [0.99468797 0.71601153 0.87072077]]


In [24]:
print(array4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


    - No se podría sumar, porque tienen distinta forma.

- En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

In [44]:
# Como primera opción, creamos una matriz de unos a partir de la matriz identidad array4, para hacer una suma a esta matriz.
array6=np.ones_like(array4)
array7=array4+array6
print(array7)

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


In [42]:
# Una segunda opción, es crear otra matriz identidad con la misma forma que el array4 y así poder realizar una suma a esta matriz.
array8=np.identity(3)
array4+array8

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

- Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

In [47]:
# Determinamos que esta sería la forma más correcta ya que utiliza el método de multiplicar de numpy.
array9=np.multiply(array4,array7)
print(array9)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]


In [48]:
# Otra opción sería de obtener el resultado de la multiplicación sería con el operador.
array10=array4*array7
print(array10)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]


- Dividid las dos matricess

In [50]:
#Mostramos las dos matrices.
print(array4)
print('---------')
print(array7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---------
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


In [56]:
# Determinamos que esta sería la forma más correcta ya que utiliza el método de dividir de numpy.
array11=np.divide(array4, array7)
print(array11)

[[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.5]]


In [55]:
# Otra opción sería de obtener el resultado de la división sería con el operador.
array12=array4/array7
print(array12)

[[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.5]]


Happy coding 😀