## Pair Programming NumPy II

### Lección 2 -NumPy II: Introducción - Modulo 2 - Sprint 1



#### Judith Mellidez y Sonia Ruiz




Seguimos trabajando con NumPy, en este caso practicaremos como acceder a distintos elementos de nuestros arrays 
y como cambiar su forma para poder hacer operaciones entre varios arrays.


In [2]:
#Importamos la libreria Numpy.
import numpy as np

1.Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:

In [10]:
#Creamos un array bidimensional con el metodo random.rand, donde coge numeros aleatorios tipo float entre 0 y 1 (incluido el 1).
array1=np.random.rand(5,3)
array1

array([[7.59851591e-01, 8.21083969e-01, 7.84232660e-01],
       [1.48433272e-04, 5.32809449e-01, 6.70211791e-03],
       [4.63451170e-01, 2.49896870e-01, 2.27698881e-01],
       [6.58628087e-01, 4.01499338e-01, 6.75737717e-01],
       [9.70190961e-02, 7.23300230e-01, 3.69799587e-01]])

- El valor de la primera fila y la segunda columna.

In [11]:
array1[0,1]

0.8210839686039006

- Los valores de la segunda fila y las dos primeras columnas.

In [12]:
array1[1,0:2]

array([1.48433272e-04, 5.32809449e-01])

- Extraed las filas pares (incluyendo la 0) y todas las columnas.

In [13]:
array1[0::2,:]

array([[0.75985159, 0.82108397, 0.78423266],
       [0.46345117, 0.24989687, 0.22769888],
       [0.0970191 , 0.72330023, 0.36979959]])

- Extraed los valores que sean mayores que 0.5.

In [14]:
array1[(array1>0.5)]

array([0.75985159, 0.82108397, 0.78423266, 0.53280945, 0.65862809,
       0.67573772, 0.72330023])

- Extraed los valores menores que 0.2 o mayores que 0.5

In [15]:
array1[(array1>0.5) | (array1<0.2)]

array([7.59851591e-01, 8.21083969e-01, 7.84232660e-01, 1.48433272e-04,
       5.32809449e-01, 6.70211791e-03, 6.58628087e-01, 6.75737717e-01,
       9.70190961e-02, 7.23300230e-01])

2.Cread dos array de tres dimensiones:

- El primero de 2 matrices, 5 filas y 3 columnas.

In [18]:
#Creamos un array bidimensional con el metodo random.randint, donde coge numeros aleatorios, tipo integer, dentro
#  del rango que le especifiquemos.
array2=np.random.randint(0,40,(2,5,3))
array2

array([[[27, 33, 10],
        [35,  9, 24],
        [11, 38, 31],
        [ 6, 34, 13],
        [19, 25, 39]],

       [[25, 27, 32],
        [ 9, 37,  6],
        [ 4,  6,  4],
        [ 7, 32,  2],
        [15, 33, 11]]])

- El segundo de 3 matrices, 2 filas y 5 columnas

In [19]:
array3=np.random.randint(0,40,(3,2,5))
array3

array([[[15, 18,  2,  6,  6],
        [28,  0, 15, 12,  3]],

       [[18, 36, 38, 20, 15],
        [ 7, 32, 16,  0, 12]],

       [[28, 34, 21,  7, 33],
        [14, 28, 28, 19,  4]]])

- Haced un análisis exploratorio de los array creados. 
Recordad que en el ejercicio de ayer nos creamos una función para esto.

In [20]:
#Creamos una funcion para extraer las propiedades de un array.
def propiedades_array(array):
    lista_array=[]
    shape=array.shape
    print('Su forma es', shape)
    size=array.size
    print('Su tamaño es', size)
    dimension=array.ndim
    print('Sus dimensiones son', dimension)
    tipo=array.dtype
    print('El tipo de dato almacenado es', tipo)
    return

In [21]:
propiedades_array(array1)

Su forma es (5, 3)
Su tamaño es 15
Sus dimensiones son 2
El tipo de dato almacenado es float64


In [22]:
propiedades_array(array2)

Su forma es (2, 5, 3)
Su tamaño es 30
Sus dimensiones son 3
El tipo de dato almacenado es int64


In [23]:
propiedades_array(array3)

Su forma es (3, 2, 5)
Su tamaño es 30
Sus dimensiones son 3
El tipo de dato almacenado es int64


- Sumad los dos arrays. ¿Podéis? ¿Por qué?

In [25]:
#No podemos efectuar la suma porque tienen formas diferentes.
np.add(array2,array3)

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

- Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen 
distintas formas hemos aprendido dos métodos:

  - .reshape()
  - .transpose()

  Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [29]:
#Aplicando el metodo reshape, cambiamos la forma al array de tal manera que ambos arrays tengan la misma estructura.
array4=np.reshape(array2,(2,3,5))
array4

array([[[27, 33, 10, 35,  9],
        [24, 11, 38, 31,  6],
        [34, 13, 19, 25, 39]],

       [[25, 27, 32,  9, 37],
        [ 6,  4,  6,  4,  7],
        [32,  2, 15, 33, 11]]])

In [31]:
#Cambiamos esta vez aplicando el metodo "".transpose()"".
array5=np.transpose(array3,(1,0,2))
array5

array([[[15, 18,  2,  6,  6],
        [18, 36, 38, 20, 15],
        [28, 34, 21,  7, 33]],

       [[28,  0, 15, 12,  3],
        [ 7, 32, 16,  0, 12],
        [14, 28, 28, 19,  4]]])

In [32]:
#Sumamos los arrays modificados.
np.add(array4,array5)

array([[[42, 51, 12, 41, 15],
        [42, 47, 76, 51, 21],
        [62, 47, 40, 32, 72]],

       [[53, 27, 47, 21, 40],
        [13, 36, 22,  4, 19],
        [46, 30, 43, 52, 15]]])

Happy coding 😀