# Ejercicios Pair Programming - Modulo 2 - Sprint 1 
## Lección 3 - NumPy III: Operaciones estadísticas y matemáticas
### Judith Mellidez y Sonia Ruiz

En esta lección hemos aprendido algunas de las operaciones matemáticas más importantes que podemos aplicar a un array. Hoy pondremos en práctica algunas de estas operaciones, además de recordar algunas de los métodos aprendidos en otras lecciones y recordar como podemos iterar por un array.

1.Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales.

In [3]:
#Importamos la libreria Numpy y creamos un array con el metodo "np.random.rand()", donde coge numeros aleatorios
#  tipo float entre 0 y 1 (incluido el 1).
import numpy as np
array1=np.random.rand(2,3,5)
array1

array([[[0.62043522, 0.89084855, 0.56455621, 0.14715773, 0.90807455],
        [0.71571876, 0.17129777, 0.58133777, 0.22754897, 0.31993751],
        [0.29017474, 0.40959578, 0.75985123, 0.47599413, 0.8099042 ]],

       [[0.3676107 , 0.91227186, 0.84466699, 0.49166098, 0.10025632],
        [0.6947252 , 0.38018154, 0.43623815, 0.17676638, 0.86150535],
        [0.36495386, 0.33959182, 0.59026532, 0.14282324, 0.40921354]]])

In [4]:
#Utilizamos el metodo "np.round()", especificando un decimal, para que nos redondee cada uno de los elementos de nuetros array.
array1=np.round(array1,decimals=1)
array1

array([[[0.6, 0.9, 0.6, 0.1, 0.9],
        [0.7, 0.2, 0.6, 0.2, 0.3],
        [0.3, 0.4, 0.8, 0.5, 0.8]],

       [[0.4, 0.9, 0.8, 0.5, 0.1],
        [0.7, 0.4, 0.4, 0.2, 0.9],
        [0.4, 0.3, 0.6, 0.1, 0.4]]])

- 2.Sobre el array creado anteriormente, calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [7]:
#Aplicando el metodo "n.mean()", calculamos la media del array y redondeamos a 1 decimal.
media_array1=round(np.mean(array1),1)
media_array1

0.5

- 3.Sobre el array creado en el paso 1,Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [8]:
#Aplicando el metodo "n.max()", calculamos el valor maximo del array y redondeamos a 1 decimal.
max_array1=round(np.max(array1),1)
max_array1

0.9

- 4.Sobre el array creado en el paso 1,calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [9]:
#Aplicando el metodo "n.min()", calculamos el valor minimo del array y redondeamos a 1 decimal.
min_array1=round(np.min(array1),1)
min_array1

0.1

5. Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.

In [22]:
array_vacio=np.empty_like(array1,int)
array_vacio
#hemos utilizado el metodo "empty_like" con int (integer) porque si lo utilizamos
#  unicamente con empty_like, nos da la misma forma y tipo del array que ya teniamos
#  guardado y sus valores, ya que es lo ultimo que tenemos almacenado en la memoria.

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

`# a modo de ejemplo. Si tenemos el siguiente array`

`[[[0.4, 0.7, 0.2, 0.9, 0.2],`

`    [0.1, 0.9, 0.6, 0.1, 0.2],`

`    [1. , 0.2, 0.1, 0.8, 0.3]],`

`   [[0. , 0.3, 0.4, 0.5, 0.1],`

`    [0.5, 0.7, 0.9, 0. , 0.8],`

`    [0.5, 0.3, 0.5, 0.8, 0.1]]])`

`# sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0`

`# nuestro array vacío debería quedar como este: `

`[[["A", "B", "C", "B", "C"],`

`    ["C", "B", "B", "C", "C"],`

`    ["D" , "C", "C", "B", "C"]],`

`   [["E" , "C", "A", "B", "C"],`

`    ["B", "B","B", "E" , "B"],`

`    ["B", "C", "B", "B", "C"]]])`


💡 Pista 💡 Tendréis que iterar por el array y cambiar los valores de la matriz vacía. Para eso tendremos que usar distintos condicionales.

In [41]:
list_array_vacio=[]
for i in array1:
    for fila in i:
        for num in fila:
            if num==media_array1:
                list_array_vacio.append('A')
            elif num==max_array1:
                list_array_vacio.append('D')
            elif num==min_array1:
                list_array_vacio.append('E')
            elif num>media_array1:
                list_array_vacio.append('B')
            elif num<media_array1:
                list_array_vacio.append('C')
print(list_array_vacio)

#hemos agrupado en las primeras condiciones if/elif las igualdades del array con respecto a la
#  media, el maximo y el minimo, y posteriormente hemos hecho el menor y mayor de la media. De
#  no ser asi, se habria cumplido la condicion de menor o mayor y no habria llegado el bucle
#  a comprobar las otras igualdades.

['B', 'D', 'B', 'E', 'D', 'B', 'C', 'B', 'C', 'C', 'C', 'C', 'B', 'A', 'B', 'C', 'D', 'B', 'A', 'E', 'B', 'C', 'C', 'C', 'D', 'C', 'C', 'B', 'E', 'C']


In [42]:
array_lista=np.array(list_array_vacio)
array_lista.reshape(2,3,5)
#hemos convertido la lista en un array unidimensional y a continuacion, le hemos
#  dado la forma del array original.

array([[['B', 'D', 'B', 'E', 'D'],
        ['B', 'C', 'B', 'C', 'C'],
        ['C', 'C', 'B', 'A', 'B']],

       [['C', 'D', 'B', 'A', 'E'],
        ['B', 'C', 'C', 'C', 'D'],
        ['C', 'C', 'B', 'E', 'C']]], dtype='<U1')

6. Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.
En este caso:
- Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1
- Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2
- Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.

In [43]:
#Empleamos el metodo ".reshape()" para cambiar la forma de un array sin cambiar sus datos, obteniendo un array
#  unidimesional de 30 elementos.
array_vacio2=array_lista.reshape(30)
array_vacio2

array(['B', 'D', 'B', 'E', 'D', 'B', 'C', 'B', 'C', 'C', 'C', 'C', 'B',
       'A', 'B', 'C', 'D', 'B', 'A', 'E', 'B', 'C', 'C', 'C', 'D', 'C',
       'C', 'B', 'E', 'C'], dtype='<U1')

In [49]:
#Generamos un array vacio con el metodo "np.empty_like()".
array_vacio2=np.empty_like(array_vacio2)
array_vacio2
#no hay que indicar que haga un array vacio de strings porque el array de origen ya
#  es un array de strings.

array(['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [ ]:
#Creamos un buble for para sustituir las letras por los numeros indicados.
list_array_vacio2=[]
for str in array_lista:
    if str=='A' or str=='B':
        list_array_vacio2.append(1)
    elif str=='C' or str=='D':
        list_array_vacio2.append(2)
    elif str=='E':
        list_array_vacio2.append(3)
print(list_array_vacio2)

[1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2]


Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [ ]:
#CReamos un array a partir de los valores obtenido en el bucle anterior. Y mediante el metodo ".reshape()" efectuamos
#  los cambios solicitados.
array_lista2=np.array(list_array_vacio2)
array_lista2.reshape(2,3,5)

array([[[1, 1, 1, 2, 1],
        [1, 2, 1, 2, 2],
        [2, 2, 1, 1, 1]],

       [[2, 1, 1, 1, 2],
        [1, 2, 2, 2, 1],
        [2, 2, 1, 2, 2]]])

Happy coding 😀