# Ejercicios Pair Programming - Modulo 2 - Sprint 1 
## Lección 1 - Pandas I: Dataframes y Series
### Judith Mellidez y Sonia Ruiz

El objetivo de la clase de hoy será crear unos cuántos DataFrames y Series a través de los siguientes ejercicios:

1.¿Qué diferencia hay entre una Serie y un DataFrame?

La diferencia principal es la dimensión de ambas estructuras. Una Serie es una estructura unidimensional (una columna, ya que la proporciona Pandas). Mientras que el DataFrame es bidimensional (una tabla).

2.Momento de trabajar con Series. Contestad a las siguientes preguntas:
- Crea dos listas:
   - Una que se llame "valores" que tenga 7 números aleatorios.
   - Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.



In [1]:
#Importamos las librerias Numpy y Pandas
import pandas as pd
import numpy as np

In [2]:
# Creamos un array bidimensional con el metodo random.randint, donde coge numeros aleatorios, tipo integer, dentro
#  del rango que le especifiquemos. Ademas creamos una lista con los dias de la semana.
valores=np.random.randint(0,10,(7))
indices=['lunes', 'martes','miercoles','jueves','viernes','sabado','domingo']


- A partir de estas dos listas cread una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [10]:
serie1=pd.Series(valores,indices)
print(serie1)

lunes        5
martes       8
miercoles    8
jueves       7
viernes      5
sabado       0
domingo      0
dtype: int64


- A partir de las dos listas anteriores cread un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí.


In [18]:
#Empleamos el metodo zip para iterar por las listas anteriores ylo almacenamos en una variable ya que el
#  metodo "zip()" en si mismo es de un solo uso.
zip1=zip(indices,valores)
zip2=list(zip1)
print(zip2)

[('lunes', 5), ('martes', 8), ('miercoles', 8), ('jueves', 7), ('viernes', 5), ('sabado', 0), ('domingo', 0)]


In [23]:
#Creamos un bucle for y un diccionario vacio donde el bucle ira iterando cada tupla creada en el zip anteriormente, donde
#  el primer elemento de cada tupla sera la key y el segundo el value.
dic1={}
for k,v in zip2:
    dic1[k]=v
print(dic1)

{'lunes': 5, 'martes': 8, 'miercoles': 8, 'jueves': 7, 'viernes': 5, 'sabado': 0, 'domingo': 0}


- Crea una Serie con el diccionario creado en el punto anterior.

In [24]:
#Creamos una serie a partir del diccionario anterior.
serie2=pd.Series(dic1)
print(serie2)

lunes        5
martes       8
miercoles    8
jueves       7
viernes      5
sabado       0
domingo      0
dtype: int64


    - A continuacion utilizamos los siguientes metodos de exploracion, para conocer los datos de nuestra serie.

- ¿Qué forma tiene esta última Serie?

In [26]:
forma2=serie2.shape
print(f'La forma de esta serie es', forma2)

La forma de esta serie es (7,)


- ¿Qué tipo de datos tiene?

In [28]:
tipo2=serie2.dtype
print(f'El tipo de esta serie es', tipo2)

El tipo de esta serie es int64


- ¿Qué tamaño tiene?

In [29]:
tamaño2=serie1.size
print(f'El tamaño de esta serie es', tamaño2)

El tamaño de esta serie es 7


- ¿Cuáles son los índices de la Serie?

In [33]:
indices2=serie2.index
print(f'Los indices de esta serie es', indices2)

Los indices de esta serie es Index(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado',
       'domingo'],
      dtype='object')


- ¿Y los values?

In [34]:
values2=serie2.values
print(f'Los values de esta serie es', values2)

Los values de esta serie es [5 8 8 7 5 0 0]


- Extraed el valor para el índice "lunes"

In [39]:
serie2.loc['lunes']

5

- Extraed el valor para el índice "lunes", "martes" y "miércoles".

In [42]:
serie2.loc[['lunes','martes','miercoles']]

lunes        5
martes       8
miercoles    8
dtype: int64

- Extraed el valor para el índice "lunes" y "domingo".

In [43]:
serie2.loc[['lunes','domingo']]

lunes      5
domingo    0
dtype: int64

3.Es el turno de los DataFrames:
- Cread un array de dos dimensiones con 4 filas y 3 columnas.

In [47]:
# Creamos un array bidimensional con el metodo random.randint, donde coge numeros aleatorios, tipo integer, dentro
#  del rango que le especifiquemos.
array1=np.random.randint(0,10,(4,3))
print(array1)

[[5 9 1]
 [2 3 2]
 [2 5 7]
 [3 0 9]]


- Convertid el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

In [48]:
#Creamos un dataframe con los valores del array anterior, añadiendo un nombre a cada una de las columnas.
df=pd.DataFrame(array1, columns=['España','Francia','Italia'])
print(df)

   España  Francia  Italia
0       5        9       1
1       2        3       2
2       2        5       7
3       3        0       9


- Descargad el archivo "medallas" y cargad el DataFrame con la siguiente línea de código:

In [28]:
#Usamos el metodo "pd.read_csv()" para crear un dataframe a partir de un archivo .csv .
df = pd.read_csv("medallas.csv", index_col=["País"])

📌 NOTA Para evitar problemas guardar el archivo medallas.csv a la misma altura (en la misma carpeta) que el jupyter donde estamos trabajando.
- Usando el loc extraed todas las columnas de la fila.

In [9]:
df.loc[:]

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

- Usando el loc extraed todas las columnas de China e Irán.

In [13]:
#El metodo ".loc()" funciona igual que el metodo ".iloc()". Se diferencian en que ".loc()" utiliza los strings
#  de las filas y columnas, mientras que ".iloc()" utiliza los indices.
df.loc[['China','Irán'],:]

Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720
Irán            4   179    181     197

- Usando el loc extraed solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

In [15]:
df.loc[['China','Irán'],['Oro','Plata','Bronce']]

Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197

- Usando el iloc extraed la información de la India. Devolved todas las columnas.

In [16]:
#Utilizamos el metodo ".iloc()" para obtener los valores de "India" a apartir de su indice.
df.iloc[5]

Unnamed: 0      6
Oro           154
Plata         202
Bronce        315
Name: India, dtype: int64

- Usando el iloc extraed todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

In [19]:
df.iloc[1::2,:]

Unnamed: 0   Oro  Plata  Bronce
País                                            
Japón                     2  1032   1037     985
Irán                      4   179    181     197
India                     6   154    202     315
Indonesia                 8   112    131     240
Corea del Norte          10    91    120     235

- Utilizando el código del ejercicio anterior, seleccionad unicamente las columnas "Oro", "Plata" y "Bronce".

In [21]:
df.iloc[1::2,[1,2,3]]

Oro  Plata  Bronce
País                                
Japón            1032   1037     985
Irán              179    181     197
India             154    202     315
Indonesia         112    131     240
Corea del Norte    91    120     235

- Contestad a las siguientes preguntas:
   - ¿Qué país consiguió más de 200 medallas de oro?
   - ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
   - ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

In [27]:
df[df.Oro>200]

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

In [28]:
df.loc[(df.Oro>200)&(df.Plata>1000)]

Unnamed: 0   Oro  Plata  Bronce
País                                  
Japón           2  1032   1037     985

In [30]:
df.loc[(df.Oro>200)|(df.Bronce>700)]

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

- Como vemos hay una columna que se llama Unnamed: 0 que no nos interesa. Eliminad esa columna.

In [36]:
#Usamos el metodo "pd.read_csv()" para crear un dataframe a partir de un archivo .csv .
df = pd.read_csv("medallas.csv", index_col=["País"])
df

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

In [37]:
#una formad de eliminar la columna pero sin sustituir la variable que contiene el DataFrame es:
df.drop(['Unnamed: 0'],axis=1)

Oro  Plata  Bronce
País                                
China            1473    994     720
Japón            1032   1037     985
Corea del Sur     745    663     827
Irán              179    181     197
Kazajistán        155    158     224
India             154    202     315
Tailandia         132    175     278
Indonesia         112    131     240
China Taipéi       99    144     276
Corea del Norte    91    120     235

In [38]:
df

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

In [39]:
# otra forma de hacerlo de manera permanente en la variable que contiene el DataFrame:
del(df['Unnamed: 0'])

In [40]:
df

Oro  Plata  Bronce
País                                
China            1473    994     720
Japón            1032   1037     985
Corea del Sur     745    663     827
Irán              179    181     197
Kazajistán        155    158     224
India             154    202     315
Tailandia         132    175     278
Indonesia         112    131     240
China Taipéi       99    144     276
Corea del Norte    91    120     235

- Cread una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

(Descargar el archivo 'medallas.csv')

In [35]:
df['total_medallas']=(df['Oro']+df['Plata'])
df

Oro  Plata  Bronce  total_medallas
País                                                
China            1473    994     720            2467
Japón            1032   1037     985            2069
Corea del Sur     745    663     827            1408
Irán              179    181     197             360
Kazajistán        155    158     224             313
India             154    202     315             356
Tailandia         132    175     278             307
Indonesia         112    131     240             243
China Taipéi       99    144     276             243
Corea del Norte    91    120     235             211

Happy coding 💪🏽